#!/usr/bin/env bash
# Regenerate the production image locks from pyproject.toml.
#
#   requirements.lock      every PyPI dependency, exact version + sha256 hashes
#                          (installed with `pip install --require-hashes`)
#   requirements-sdk.lock  the constellation-node-sdk git pin (a VCS requirement
#                          cannot carry a hash, so pip installs it separately,
#                          pinned to the release commit the ledger names)
#
# Usage: bash tools/lock_requirements.sh   (needs uv)
set -euo pipefail
cd "$(dirname "$0")/.."
uv pip compile pyproject.toml --python-version 3.12 --generate-hashes -o requirements.lock.tmp
python3 - <<'PY'
import re
from pathlib import Path
src = Path("requirements.lock.tmp").read_text().splitlines(keepends=True)
sdk, rest, i = [], [], 0
while i < len(src):
    line = src[i]
    if line.startswith("constellation-node-sdk @ "):
        # a git requirement has no hash lines; take its "# via" comment lines too
        sdk.append(line.rstrip(" \\\n") + "\n")
        i += 1
        while i < len(src) and src[i].startswith("    #"):
            i += 1
        continue
    rest.append(line)
    i += 1
header = "# Generated by tools/lock_requirements.sh -- do not edit by hand.\n"
Path("requirements.lock").write_text(header + "".join(rest))
Path("requirements-sdk.lock").write_text(header + "".join(sdk))
Path("requirements.lock.tmp").unlink()
PY
echo "wrote requirements.lock ($(grep -c '==' requirements.lock) pins) and requirements-sdk.lock"
