#!/usr/bin/env bash
# Regenerate the container image lock (requirements.lock) from pyproject.toml.
#
# Every dependency is pinned to an exact version with sha256 hashes so the
# image installs with `pip install --require-hashes`. constellation-node-sdk is
# declared in pyproject.toml as a git dependency, which pip cannot hash-verify;
# the lock therefore carries the SAME commit as GitHub's source archive URL
# (github.com/<org>/<repo>/archive/<sha>.tar.gz) with the archive's sha256, so
# the SDK is hash-verified like everything else and stays pinned to the release
# commit named in Gate_SDK's RELEASE_IDENTITY_LEDGER.
#
# Usage: bash <this script>   (needs uv, curl, python3)
set -euo pipefail
cd "$(dirname "$0")/.."
uv pip compile pyproject.toml --python-version 3.12 --generate-hashes -o requirements.lock.tmp
python3 - <<'PY'
import hashlib, re, subprocess, sys, urllib.request
from pathlib import Path
src = Path("requirements.lock.tmp").read_text().splitlines(keepends=True)
out, i = [], 0
git_re = re.compile(r"^(?P<name>[A-Za-z0-9_.-]+) @ git\+https://github\.com/(?P<org>[^/]+)/(?P<repo>[^/@.]+?)(?:\.git)?@(?P<sha>[0-9a-f]{40})")
while i < len(src):
    line = src[i]
    m = git_re.match(line)
    if m:
        url = f"https://github.com/{m['org']}/{m['repo']}/archive/{m['sha']}.tar.gz"
        with urllib.request.urlopen(url) as resp:  # noqa: S310 - fixed https host
            digest = hashlib.sha256(resp.read()).hexdigest()
        out.append(f"{m['name']} @ {url} \\\n    --hash=sha256:{digest}\n")
        i += 1
        while i < len(src) and src[i].startswith("    #"):
            out.append(src[i]); i += 1
        continue
    out.append(line); i += 1
# One requirement per line: continuation lines are joined and the "# via"
# annotations dropped. Every hash is kept, so verification strength is
# unchanged; the file is simply ~20x fewer lines, which keeps a lock refresh
# from dominating a pull request's line count.
compact, current = [], ""
for raw in "".join(out).splitlines(keepends=True):
    if raw.startswith("#") and not current:
        continue
    if raw.startswith("    #"):
        continue
    stripped = raw.rstrip("\n")
    if stripped.endswith(" \\"):
        current += stripped[:-2].strip() + " "
        continue
    current += stripped.strip()
    if current.strip():
        compact.append(current.strip() + "\n")
    current = ""
header = ("# Generated by the lock_requirements.sh script -- do not edit by hand.\n"
          "# Install with: pip install --require-hashes --no-deps -r requirements.lock\n"
          "# One requirement per line, every sha256 kept inline.\n")
Path("requirements.lock").write_text(header + "".join(compact))
Path("requirements.lock.tmp").unlink()
PY
echo "wrote requirements.lock ($(grep -c -- '--hash' requirements.lock) hashes)"
